name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest

    - name: Build Docker Image
      run: |
        docker build -t inventory-bot .

    - name: Push Docker Image (example)
      run: |
        echo "Pushing to container registry (mocked)"

    - name: Tag and Release
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git tag v1.0.0
        git push origin --tags